id: MTB-PL1-BC-HI-1
title: Block use of NodePort services
benchmarkType: Behavioral Check
category: Host Isolation
description: Tenants should not be able to create services of type NodePort.
remediation: Use a policy engine such as [OPA/Gatekeeper](https://github.com/open-policy-agent/gatekeeper) or [Kyverno](https://kyverno.io) to block NodePort Services.
profileLevel: 1