id: MTB-PL1-CC-CPI-1
title: Block access to cluster resources
benchmarkType: Configuration Check
category: Control Plane Isolation
description: Tenants should not be able to view, edit, create, or delete cluster (non-namespaced) resources such Node, ClusterRole, ClusterRoleBinding, etc.
remediation:
profileLevel: 1
