id: MTB-PL1-BC-CPI-4
title: Require run as non-root user
benchmarkType: Behavioral Check
category: Control Plane Isolation
description: Processes in containers run as the root user (uid 0), by default. To prevent potential compromise of container hosts, specify a least privileged user ID when building the container image and require that application containers run as non root users.
remediation: Define a PodSecurityPolicy a runAsUser rule set to MustRunAsNonRoot and map the policy to each tenant's namespace, or use a policy engine such as OPA/Gatekeeper or Kyverno to enforce that runAsNonRoot is set to true for tenant pods.
profileLevel: 1