id: MTB-PL1-BC-HI-5
title: Block use of host IPC
benchmarkType: Behavioral Check
category: Host Isolation
description: Tenants should not be allowed to share the host's inter-process communication (IPC) namespace.
remediation: Define a `PodSecurityPolicy` with `hostIPC` set to `false` and map the policy to each tenant's namespace, or use a policy engine such as [OPA/Gatekeeper](https://github.com/open-policy-agent/gatekeeper) or [Kyverno](https://kyverno.io) to enforce that `hostPID` cannot be set to `true`.
profileLevel: 1