id: MTB-PL1-BC-HI-1
title: Block use of bind mounts 
benchmarkType: Behavioral Check
category: Host Protection
description: Tenants should not be able to mount host volumes and folders (bind mounts).
remediation: Define a `PodSecurityPolicy` that restricts hostPath volumes and map the policy to each tenant namespace, or use a policy engine such as [OPA/Gatekeeper](https://github.com/open-policy-agent/gatekeeper) or [Kyverno](https://kyverno.io) to enforce that a `hostPath` volume cannot be used.
profileLevel: 1